
import { Translations } from './types';

export const TRANSLATIONS: Translations = {
  EN: {
    login: "Login",
    username: "Username",
    password: "Password",
    createPassword: "Create Password",
    changePassword: "Change Password",
    oldPassword: "Old Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordUpdated: "Password updated successfully",
    passwordsDoNotMatch: "Passwords do not match",
    wrongOldPassword: "Old password is incorrect",
    role: "Role",
    designation: "Designation",
    admin: "Admin",
    manager: "Manager",
    operator: "Operator",
    user: "User",
    createUser: "Create New User",
    email: "Email (Optional)",
    contactNumber: "Contact Number",
    branch: "Branch",
    addNewBranch: "Add New Branch",
    addNewEquipment: "Add New Equipment",
    addNewRepair: "New Repair Request",
    submit: "Submit",
    approve: "Approve",
    reject: "Reject",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    dashboard: "Dashboard",
    equipment: "Equipment",
    branches: "Branches",
    transfer: "Equipment Transfer",
    repairs: "Repair Requests",
    reports: "Reports",
    adminPanel: "Admin Panel",
    totalBranches: "Total Branches",
    totalEquipment: "Total Equipment",
    notifications: "Notifications",
    transferRequest: "Transfer Request",
    targetBranch: "Target Branch",
    reason: "Reason",
    rejectionReason: "Rejection Reason",
    faultLevel: "Fault Level (1-10)",
    equipmentType: "Equipment Type",
    companyId: "Company ID",
    make: "Make",
    model: "Model",
    serialNumber: "Serial Number",
    power: "Power",
    condition: "Condition",
    managerName: "Manager Name",
    location: "Location",
    branchCode: "Branch Code",
    branchName: "Branch Name",
    search: "Search...",
    logout: "Logout",
    selectEquipment: "Select Equipment",
    selectBranch: "Select Branch",
    status: "Status",
    userApprovalNeeded: "New user approval needed",
    transferAction: "Action Required: Transfer Request",
    repairRequestSent: "Repair Request Sent",
    equipmentImage: "Equipment Image",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    details: "Details",
    selectUser: "Select User",
    addNew: "Add New",
    date: "Date",
    faults: "Faults",
    minOneFault: "At least one fault must be entered",
    remarks: "Remarks",
    faultPlaceholder: "Describe fault",
    activity: "Activity",
    history: "History",
    allBranches: "All Branches",
    noHistoryFound: "No history found for this branch",
    systemAdmin: "System Admin"
  },
  AR: {
    login: "تسجيل الدخول",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    createPassword: "إنشاء كلمة مرور",
    changePassword: "تغيير كلمة المرور",
    oldPassword: "كلمة المرور القديمة",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور الجديدة",
    passwordUpdated: "تم تحديث كلمة المرور بنجاح",
    passwordsDoNotMatch: "كلمات المرور غير متطابقة",
    wrongOldPassword: "كلمة المرور القديمة غير صحيحة",
    role: "الدور",
    designation: "المسمى الوظيفي",
    admin: "مسؤول",
    manager: "مدير",
    operator: "مشغل",
    user: "مستخدم",
    createUser: "إنشاء مستخدم جديد",
    email: "البريد الإلكتروني (اختياري)",
    contactNumber: "رقم الاتصال",
    branch: "الفرع",
    addNewBranch: "إضافة فرع جديد",
    addNewEquipment: "إضافة معدات جديدة",
    addNewRepair: "طلب إصلاح جديد",
    submit: "إرسال",
    approve: "موافقة",
    reject: "رفض",
    pending: "قيد الانتظار",
    approved: "تمت الموافقة",
    rejected: "مرفوض",
    dashboard: "لوحة القيادة",
    equipment: "المعدات",
    branches: "الفروع",
    transfer: "نقل المعدات",
    repairs: "طلبات الإصلاح",
    reports: "التقارير",
    adminPanel: "لوحة المسؤول",
    totalBranches: "إجمالي الفروع",
    totalEquipment: "إجمالي المعدات",
    notifications: "التنبيهات",
    transferRequest: "طلب نقل",
    targetBranch: "الفرع المستهدف",
    reason: "السبب",
    rejectionReason: "سبب الرفض",
    faultLevel: "مستوى العطل (1-10)",
    equipmentType: "نوع المعدات",
    companyId: "معرف الشركة",
    make: "الشركة المصنعة",
    model: "الموديل",
    serialNumber: "الرقم التسلسلي",
    power: "الطاقة",
    condition: "الحالة",
    managerName: "اسم المدير",
    location: "الموقع",
    branchCode: "كود الفرع",
    branchName: "اسم الفرع",
    search: "بحث...",
    logout: "تسجيل الخروج",
    selectEquipment: "اختر المعدات",
    selectBranch: "اختر الفرع",
    status: "الحالة",
    userApprovalNeeded: "مطلوب الموافقة على مستخدم جديد",
    transferAction: "مطلوب إجراء: طلب نقل",
    repairRequestSent: "تم إرسال طلب الإصلاح",
    equipmentImage: "صورة المعدات",
    edit: "تعديل",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    details: "تفاصيل",
    selectUser: "اختر المستخدم",
    addNew: "إضافة جديد",
    date: "التاريخ",
    faults: "الأعطال",
    minOneFault: "يجب إدخال عطل واحد على الأقل",
    remarks: "ملاحظات",
    faultPlaceholder: "وصف العطل",
    activity: "النشاط",
    history: "السجل",
    allBranches: "جميع الفروع",
    noHistoryFound: "لم يتم العثور على سجل لهذا الفرع",
    systemAdmin: "مسؤول النظام"
  }
};
